### ISSUE TITLE
Wavetorch cannot be imported

### ISSUE THREAD

**Issue by linwanting** [fancompute/wavetorch#9]
import wavetorch

  File "G:\Anaconda\lib\site-packages\wavetorch\__init__.py", line 1, in <module>
    from . import rnn, cell, geom, source, probe, data, plot, utils, io

ImportError: cannot import name 'data' from 'wavetorch' (G:\Anaconda\lib\site-packages\wavetorch\__init__.py

**Comment by acse-wz19** [comment]
The same problem for me after pip install wavetorch

**Comment by ianwilliamson** [comment]
Looks like that directory is missing from the pip package for some reason. You can just download the code from this repo instead.

**Comment by acse-wz19** [comment]
Yes, I also try to download it directly from GitHub, but it always happens import error.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ian Williamson <notifications@github.com>
发送时间: Saturday, October 10, 2020 5:41:42 AM
收件人: fancompute/wavetorch <wavetorch@noreply.github.com>
抄送: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>; Comment <comment@noreply.github.com>
主题: Re: [fancompute/wavetorch] Wavetorch cannot be imported (#9)


This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Looks like that directory is missing from the pip package for some reason. You can just download the code from this repo instead.

―

**Comment by acse-wz19** [comment]
The platform I used is Google Colab.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>
发送时间: Saturday, October 10, 2020 7:37:03 AM
收件人: fancompute/wavetorch <reply@reply.github.com>; fancompute/wavetorch <wavetorch@noreply.github.com>
抄送: Comment <comment@noreply.github.com>
主题: Re: [fancompute/wavetorch] Wavetorch cannot be imported (#9)

Yes, I also try to download it directly from GitHub, but it always happens import error.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ian Williamson <notifications@github.com>
发送时间: Saturday, October 10, 2020 5:41:42 AM
收件人: fancompute/wavetorch <wavetorch@noreply.github.com>
抄送: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>; Comment <comment@noreply.github.com>
主题: Re: [fancompute/wavetorch] Wavetorch cannot be imported (#9)


This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Looks like that directory is missing from the pip package for some reason. You can just download the code from this repo instead.

―

**Comment by Kshitiz-Bansal** [comment]
I have a similar issue: 
```
Traceback (most recent call last):
  File "./study/vowel_train.py", line 5, in <module>
    import wavetorch
  File "/home/chezzyfries/.local/lib/python3.8/site-packages/wavetorch/__init__.py", line 1, in <module>
    from . import rnn, cell, geom, source, probe, data, plot, utils, io
ImportError: cannot import name 'data' from partially initialized module 'wavetorch' (most likely due to a circular import) (/home/chezzyfries/.local/lib/python3.8/site-packages/wavetorch/__init__.py)
```

I have tried using both pip install wavetorch and installing wavetorch from the code in repo. 
Please let me know if there is a known solution to this.


UPDATE: It works on copying the /wavetorch/data folder from this repo to pythonX.X/site-packages/wavetorch

**Comment by lonnietc** [comment]
Hello,

I am getting the same errors when I am trying to use it with Python 3.11.4 on Windows 10 (x64).

Are there any updates to get this to work?
Thanks
